### PR TITLE
feat: Do not return `null` as analyticsUrl for CI=true

### PR DESCRIPTION
**Pull request by pgrzesik**
We would like to record events from `CI` as well as we plan to introduce CI detection and enrich analytics events with that information

Note: The plan is to release it as a major version to avoid changing behavior for older versions which won't include information about `CI`

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
Thanks @pgrzesik 

If we want to publish it as breaking change (which triggers new major release), we need to indicate this as breaking change  in commit message.

**Comment by pgrzesik** [comment]
Totally :+1: I've also started wondering a bit more about this specific check in wider context and what impact it could have e.g. on `components` - if I understand correctly, at the moment `components` only use that to trigger notifications and it totally makes sense to avoid triggering notifications in CI, not only for `components` but for Framework as well. Do you think it's safe to change it as if I'm not mistaken it will report notifications for CI for people now?

**Comment by medikoo** [comment]
> if I understand correctly, at the moment components only use that to trigger notifications and it totally makes sense to avoid triggering notifications in CI

I'm not sure if it's a big concern. I think main reason for making this a breaking change, is that thanks to that we will not mix _untracked_ and _tracked_ CI events in scope of same version of a Framework, and that will allow us to keep data reliable in metrics service Dynamodb

**Comment by pgrzesik** [comment]
That's correct @medikoo - what I was worried about is that now additonally, for all new versions, notifications can be also triggered for `CI` deployments, which this setting was preventing in a lot of cases.

**Review by medikoo — DISMISSED** [review]
👍 

I would just reword the commit. At least `No longer return null` feels very internal, and implementation specific.

I think it should be more something as: _Expose analytics server URL unconditionally (and not just in non-CI environments)._.

This message is expected to land as is in changelog, and unless justified I would not describe changes using JS language specific terms. Ideally if implementation details are black boxed

**Comment by pgrzesik** [comment]
Good suggestion, I've reworded the commit a little bit :+1:

**Review by medikoo — APPROVED** [review]
Looks great 👍

**Pull request merged**
